### ISSUE TITLE
Basic System Components

### ISSUE THREAD

**Issue by jmcounters** [ConsenSys/quorum-dev-quickstart#219]
Hi!

I'm new to Quorum and I am following some activities/questions to learn it but I am struggling to find them in the documentations. I have successfully deployed the quickstart and in need of answers on how to demonstrate/show the following via CLI or any tools that came with the quickstart tool:

1. Basic system components of Quorum and how they interface with each other to form a blockchain network.
2. How to use GETH to invoke JSON RPC API to perform operation to accounts, nodes and transactions.
3. Using the tools and CLI:
- How to inspect nodes/peers information
- How to inspect the chain, blocks and transaction information
- How to create wallets/accounts and transferring Ether between accounts

I would welcome any links to documentation for each and guidance/steps for the others.

Thanks!

**Comment by jmcounters** [comment]
hi @joshuafernandes .

Good day!

Is this something you can help me with? I'm struggling to find resources particularly on items 1 and 2.

Thank you in advance!

**Comment by joshuafernandes** [comment]
Hi @jmcounters 

How's things going? Could you please elaborate on your use case and requirements? It might be easier explaining things with that in mind.

When you are learning how things working through the tutorials by hand https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-qbft-network/ rather than the quickstart until you are familiar with the concepts (https://consensys.net/docs/goquorum/en/latest/concepts/blockchain-basics/)

Then move on to concepts like permissioning followed by privacy and then DApps

>1. Basic system components of Quorum and how they interface with each other to form a blockchain network.

In general, the basics are https://consensys.net/docs/goquorum/en/latest/concepts/blockchain-basics/ and https://consensys.net/docs/goquorum/en/latest/concepts/blockchain-basics/blockchain-components/ 

Nodes or clients (https://consensys.net/docs/goquorum/en/latest/concepts/architecture/) agree on blocks with a consensus mechanism (https://consensys.net/docs/goquorum/en/latest/concepts/consensus/) to create blocks.

> How to use GETH to invoke JSON RPC API to perform operation to accounts, nodes and transactions.

Geth is the client GoQuorum is based on. To interact with the client via cli, ws or RPC https://consensys.net/docs/goquorum/en/latest/develop/connecting-to-a-node/?h=geth+attach

> How to inspect nodes/peers information,  inspect the chain, blocks and transaction information 
https://geth.ethereum.org/docs/rpc/ns-admin#admin_peers
Also refer to the net namespace. Follow the links here https://consensys.net/docs/goquorum/en/latest/develop/json-rpc-apis/

Also refer to the monitoring doco 

> How to create wallets/accounts and transferring Ether between accounts
Use metamask for a wallet and here's docs to tranfer funds https://consensys.net/docs/goquorum/en/latest/tutorials/contracts/account-funds-transfers/

Please note, almost all of the above is covered in the quickstart. Questions like these are better suited for Discord rather than here as they will serve a wider audience and you will engage with other contributors,

Cheers


> hi @joshuafernandes .
> 
> Good day!
> 
> Is this something you can help me with? I'm struggling to find resources particularly on items 1 and 2.
> 
> Thank you in advance!
