### ISSUE TITLE
goquorum Multihost setup 

### ISSUE THREAD

**Issue by Shweta-hlf** [ConsenSys/quorum-dev-quickstart#225]
Hi team,
I am trying to multihost setup using this quorum-dev-quickstart using docker extra host. 2 quorum/tessera node on host 1 and 1 quorum/tessara on second host.

But quourm/tessera nodes are not started in healthy status.

can any one try multhost set up.Please help me out here asap.

Regards!!

**Comment by joshuafernandes** [comment]
Hello @Shweta-hlf this belongs in the discord channels and not here. I'd also recommend you put a diagram or something similar of what you are trying to do so that other folk can help you out ie which client, which options you've selected etc. You can use something along these lines for multiple hosts https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-qbft-network/ Bear in mind you need to change the IP's to the host's IP and make sure that both hosts can communicate with each other
