### ISSUE TITLE
How can I add one more member node and orion node in docker template ? 

### ISSUE THREAD

**Issue by DavidSunGoldhub** [ConsenSys/quorum-dev-quickstart#26]
Hi , I wanna create a one more backup node on member1 and orion1 . Those backup are sharing same key and config , 
here is my config file

member1backorion:
    << : *orion-def
    environment:
      - ORION_OTHERNODES=http://member2orion:8080/,http://member3orion:8080/,http://member1orion:8080/
      - ORION_NODEURL=http://member1backorion:8080
      - ORION_CLIENTURL=http://member1backorion:8888
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion1:/keys/
      - ./logs/orion:/var/log/
      - ./config/orion/log-config.xml:/config/log-config.xml
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.126

member1backbesu:
    << : *besu-def
    entrypoint:
      - /bin/bash
      - -c
      - |
        while [ ! -f "/opt/besu/public-keys/bootnode_pubkey" ]; do sleep 5; done ;
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --min-gas-price=0 \
        --privacy-enabled \
        --privacy-url=http://member1backorion:8888 \
        --privacy-public-key-file=/config/orion/orion.pub \
        --privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false} \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_API:-IBFT} \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_API:-IBFT} ;
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/member1/keys:/opt/besu/keys
      - ./config/orion/networkFiles/orion1/nodeKey.pub:/config/orion/orion.pub
    depends_on:
      - validator1
      - member1backorion
    ports:
      - 20010:8545/tcp
      - 20011:8546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.116

But when I shoot a command resume.sh then it report a error when start. 
Beside that how can I add the member1backorion to the node-whitelist ? 

Thanks
DaDa

**Comment by joshuafernandes** [comment]
Hello @DavidSunGoldhub 

What is the error that you see?

To add another node edit the compose file and add them in there. You will likely need to create new keys for both Orion and Besu and then run `./run.sh`, and then you can `stop.sh` and `resume.sh`

**To add the Besu node:**
Do you mean `host-whitelist` - if so that is set to `*` and doesn't need to be changed. https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/templates/besu/config/besu/config.toml#L4

If you are running permissions, you can add nodes to an existing network like so: https://besu.hyperledger.org/en/stable/Tutorials/Permissioning/Create-Permissioned-Network/#8-add-enode-urls-for-nodes-to-permissions-configuration-file

**To add the Orion node:**
The `ORION_OTHERNODES` pointing to the other 2 nodes should take care of, Alternatively you can use the APIs

A privacy group is also a good option for a group of Orion nodes. https://docs.orion.consensys.net/en/latest/Concepts/Privacy-Groups/

And if you wanted to run Orion in HA https://docs.orion.consensys.net/en/latest/HowTo/High-Availability/

Cheers

**Comment by eu09** [comment]
Thanks for your help . please close this case.
