### ISSUE TITLE
image not displayed

### ISSUE THREAD

**Issue by kentimsit** [ConsenSys/quorum-dev-quickstart#41]
The doc file https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/gquorum/README.md
references an image 
https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/gquorum/static/blockchain-network.png
which is missing

**Comment by joshuafernandes** [comment]
Hi @kentimsit 

This is by design - it shows up in the right place when its run via `npx quorum-dev-quickstart` or in the repo by doing `npm run build && npm run start` which puts it in the right structure under a folder (defaults to `quourm-test-network`, but the user can override). But when view raw its a lot of templates to keep the duplication down to a minimum.

Cheers
Josh
