### ISSUE TITLE
Broken image link in README

### ISSUE THREAD

**Issue by hhubik** [ConsenSys/quorum-dev-quickstart#68]
The following link in the README page is broken:
https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/besu/static/blockchain-network.png

**Comment by joshuafernandes** [comment]
Hi @hhubik 

Is the readme file in question https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/besu/README.md ?

If so this is by design, to keep things dry. When the tool is installed via npx the images and templates are fused, wherein the paths are correct for the Readme.md of the Besu or Quorum variant

**Comment by hhubik** [comment]
@joshuafernandes Yes, it is.  Thanks for the explanation.
